Update install scripts for clang-format
Summary:
Many and various fixes—the scripts still need a lot of work.

  - Fixed the brew install script
  - Fixed the clang-format install script to update clang-format if an update exists.
  - Fixed `if [ ! `some_command` ]; then` invocations, which doesn't do what the original authors seemed to have thought it does.
  - Removed all `set -e` from bash scripts... there's no need to echo everything under the sun.
  - Added `set -o errexit` for simple scripts so the script would just bail if any one command failed.
  - Lowered general verbosity in some places.

Reviewers: O1 Material components iOS, junius, featherless

Reviewed By: O1 Material components iOS, junius

Subscribers: ajsecord

Tags: #material_components_ios

Differential Revision: http://codereview.cc/D1035

diff --git a/scripts/build_all_pod_projects b/scripts/build_all_pod_projects
--- a/scripts/build_all_pod_projects
+++ b/scripts/build_all_pod_projects
@@ -14,20 +14,28 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-find . -name 'Podfile' | while read path; do
+set -o errexit
+
+build_log=build_log.txt
+find * -name 'Podfile' | while read path; do
   project_dir=$(dirname $path)
-  
-  echo "Entering $project_dir..."
+  echo "Building in $project_dir..."
+  pushd $(dirname $path) >/dev/null
 
-  pushd $project_dir >> /dev/null
-
-  pod install || { echo "Failed to run pod install."; exit 1; }
+  rm -rf Pods
+  pod install --silent
 
   workspace=$(find . -d 1 -name '*.xcworkspace')
   scheme=$(xcodebuild build -workspace $workspace -list | grep "Information about workspace" | cut -d'"' -f2)
-  xcodebuild clean -workspace $workspace -scheme $scheme
-  xcodebuild build -workspace $workspace -scheme $scheme \
-    || { echo "Failed to build $workspace."; exit 1; }
+  xcodebuild clean -workspace $workspace -scheme $scheme >/dev/null
+  
+  if ! xcodebuild build -workspace $workspace -scheme $scheme >$build_log 2>&1; then
+    echo "Failed to build $scheme in $workspace, log left in $project_dir/$build_log."
+    echo "Continuing with next project..."
+  else
+    rm $build_log
+    echo "Done."
+  fi
 
-  popd >> /dev/null
+  popd >/dev/null
 done
