Generalized the check_components script.
* Renamed `missing_readme` to `readme`.
* Added documentation to the `scripts/check` directory.
* Disabled the `scripts/check/missing_example_language` script.

diff --git a/scripts/check_components b/scripts/check_components
--- a/scripts/check_components
+++ b/scripts/check_components
@@ -14,7 +14,60 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-for check in scripts/check/*; do
-  echo "Each of the following components is $(basename $check | sed 's/_/ /g'):"
-  $check
+# To check all components:
+#
+# $ check_components
+#
+# To check specific components:
+#
+# $ check_components path/to/component [path/to/component [...]]
+
+# Check for verbosity command-line option.
+if [[ ( $# -gt 0 ) && ( "$1" -eq "-v" ) ]]; then
+  readonly VERBOSE=1
+  shift 1
+else
+  readonly VERBOSE=0
+fi
+
+readonly SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+readonly ROOT_DIR=$(dirname "$SCRIPTS_DIR")
+[[ $VERBOSE -eq 0 ]] || echo "SCRIPTS_DIR: $SCRIPTS_DIR"
+[[ $VERBOSE -eq 0 ]] || echo "ROOT_DIR: $ROOT_DIR"
+
+# If no component listed on the command line, find them all.
+if [[ $# -eq 0 ]]; then
+  readonly PUBLIC_COMPONENTS=$(cd $ROOT_DIR && find components -maxdepth 1 -type d | grep -v "components$" | grep -v "components/private$")
+  readonly PRIVATE_COMPONENTS=$(cd $ROOT_DIR && find components/private -maxdepth 1 -type d | grep -v "components/private$")
+  readonly COMPONENTS="$PUBLIC_COMPONENTS $PRIVATE_COMPONENTS"
+else
+  readonly COMPONENTS=$*
+fi
+[[ $VERBOSE -eq 0 ]] || echo "COMPONENTS: $COMPONENTS"
+
+# Find all the check scripts.
+readonly CHECKS=$(find $SCRIPTS_DIR/check -type f -perm +111)
+[[ $VERBOSE -eq 0 ]] || echo "CHECKS: $CHECKS"
+
+# Run through each component, running each check in turn.
+# Keep track of the number that fail any check.
+failure_count=0
+for component in $COMPONENTS; do 
+  all_checks_passed=1
+  for check in $CHECKS; do
+    $check $ROOT_DIR/$component
+    if [[ $? -ne 0 ]]; then
+      all_checks_passed=0
+    fi
+  done
+
+  if [[ $all_checks_passed -ne 1 ]]; then
+    failure_count=$((failure_count+1))
+  fi
 done
+
+if [[ $failure_count -eq 0 ]]; then
+  echo All components pass.
+else
+  echo $failure_count "component(s) failed the checks."
+fi
