[Cards] Add accessibility documentation - use or remove images

diff --git a/scripts/generate_readme b/scripts/generate_readme
--- a/scripts/generate_readme
+++ b/scripts/generate_readme
@@ -27,11 +27,12 @@ if [ "$#" -ne 1 ]; then
   exit 1
 fi
 
-command -v jazzy >/dev/null 2>&1 || { 
-  echo >&2 "Cannot find jazzy. jazzy is required to generate API links. To install try:"
-  echo >&2 "[sudo] gem install jazzy"
+JAZZY_VERSION=`jazzy --version`
+if [[ $? != 0 ]]; then
+  echo "Cannot find jazzy. jazzy is required to generate API links. To install try:"
+  echo "[sudo] gem install jazzy"
   exit 1
-}
+fi
 
 # Generates a list of urls to APIs
 # Args: $1 - Jazzy API type name. E.g. Classes
