Tabs, why???

diff --git a/scripts/generate_readme b/scripts/generate_readme
--- a/scripts/generate_readme
+++ b/scripts/generate_readme
@@ -29,9 +29,9 @@ fi
 
 JAZZY_VERSION=`jazzy --version`
 if [[ $? != 0 ]]; then
-	echo "Cannot find jazzy. jazzy is required to generate API links. To install try:"
-	echo "[sudo] gem install jazzy"
-	exit 1
+  echo "Cannot find jazzy. jazzy is required to generate API links. To install try:"
+  echo "[sudo] gem install jazzy"
+  exit 1
 fi
 
 # Generates a list of urls to APIs
