API diff.

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -144,7 +144,7 @@ cut_release() {
   if ! grep "# #develop#" "$rootdir/CHANGELOG.md" >> /dev/null; then
     echo "Generating API diff..."
     CHANGELOG_TMP_PATH=$(mktemp -d)
-    "$dir/release_tools/api_diff" origin/stable release-candidate | tee "$CHANGELOG_TMP_PATH/api_diff"
+    generate_release_apidiff | tee "$CHANGELOG_TMP_PATH/api_diff"
 
     CHANGELOG_PATH=$(cat "$CHANGELOG_TMP_PATH/api_diff" | grep "Changelog: " | cut -d':' -f2)
 
@@ -417,12 +417,97 @@ publish_release() {
 
 generate_release_apidiff() {
   CHANGELOG_TMP_PATH=$(mktemp -d)
-  # TODO: Consolidate api_diff here.
-  "$dir/release_tools/api_diff" origin/stable $(get_latest_branch) | tee "$CHANGELOG_TMP_PATH/api_diff"
 
-  CHANGELOG_PATH=$(cat "$CHANGELOG_TMP_PATH/api_diff" | grep "Changelog: " | cut -d' ' -f2-)
+  validate_commit() {
+    git cat-file -t $1 >> /dev/null 2> /dev/null || { echo "$1 is not a valid commit."; exit 1; }
+  }
 
-  cat "$CHANGELOG_PATH"
+  # Verify commits
+  old_commit=$(git rev-list -n 1 origin/stable)
+  new_commit=$(git rev-list -n 1 $(get_latest_branch))
+
+  if [[ -z "$old_commit" || -z "$new_commit" ]]; then
+    echo "Unable to get commit shas."
+    exit 1
+  fi
+
+  validate_commit $old_commit
+  validate_commit $new_commit
+
+  TMP_PATH=$(mktemp -d)
+  OLD_ROOT_PATH="$TMP_PATH/old"
+  NEW_ROOT_PATH="$TMP_PATH/new"
+  clean_clones() {
+    if [ ! -z "$OLD_ROOT_PATH" ]; then
+      rm -rf "$OLD_ROOT_PATH"
+    fi
+    if [ ! -z "$NEW_ROOT_PATH" ]; then
+      rm -rf "$NEW_ROOT_PATH"
+    fi
+  }
+  trap clean_clones EXIT
+  "$dir/temporary_clone_at_ref" "$OLD_ROOT_PATH" $old_commit
+  "$dir/temporary_clone_at_ref" "$NEW_ROOT_PATH" $new_commit
+
+  # Find command in all component src directories and grab search path for "Material$component.h"
+  old_header_search_paths=""
+  new_header_search_paths=""
+  for d in $NEW_ROOT_PATH/components/*/src; do
+    folder=$(dirname $d)
+    component=$(basename $folder)
+    old_header_search_paths="$old_header_search_paths --oldargs -I$OLD_ROOT_PATH/components/$component/src/ "
+    new_header_search_paths="$new_header_search_paths --newargs -I$NEW_ROOT_PATH/components/$component/src/ "
+  done
+
+  if [ ! -f "$dir/external/material-motion-apidiff/src/pathapidiff" ]; then
+    git submodule update --init --recursive
+  fi
+
+  ALL_CHANGELOG_PATH="$TMP_PATH/changelog"
+  ALL_ERROR_LOG_PATH="$TMP_PATH/errlog"
+
+  echo "Changelog: $ALL_CHANGELOG_PATH"
+  echo "Errors: $ALL_ERROR_LOG_PATH"
+
+  # Run new pathdiff script on each umbrella header in array
+  for path_to_component in $(generate_release_components | grep -v "private"); do
+    component=$(basename $path_to_component)
+
+    echo -n "Diffing $component..."
+
+    if [ ! -d "$OLD_ROOT_PATH/components/$path_to_component/src" ]; then
+      echo >> $ALL_CHANGELOG_PATH
+      echo "### $component" >> $ALL_CHANGELOG_PATH
+      echo >> $ALL_CHANGELOG_PATH
+      echo "**New component.**" >> $ALL_CHANGELOG_PATH
+
+      echo "New!"
+      continue
+    fi
+
+    CHANGES_PATH="$TMP_PATH/${component}changes"
+    ERROR_PATH="$TMP_PATH/${component}errlog"
+
+    "$dir/external/material-motion-apidiff/src/pathapidiff" \
+       "$OLD_ROOT_PATH" "$NEW_ROOT_PATH" objc "/components/$component/src/Material$component.h" \
+       >> "$CHANGES_PATH" \
+       2>> "$ERROR_PATH"
+
+    if [ -s "$CHANGES_PATH" ]; then
+      echo >> $ALL_CHANGELOG_PATH
+      echo "### $component" >> $ALL_CHANGELOG_PATH
+      cat "$CHANGES_PATH" >> $ALL_CHANGELOG_PATH
+
+      echo -n " Changes detected."
+    fi
+
+    if [ -s "$ERROR_PATH" ]; then
+      echo "### $component" >> "$ALL_ERROR_LOG_PATH"
+      cat "$ERROR_PATH" >> "$ALL_ERROR_LOG_PATH"
+    fi
+
+    echo
+  done
 }
 
 generate_release_authors() {
