corrected bash if grep statement

diff --git a/scripts/test_all b/scripts/test_all
--- a/scripts/test_all
+++ b/scripts/test_all
@@ -63,11 +63,10 @@ for workspace_scheme in $WORKSPACE_SCHEMES; do
 done
 
 echo checking pod push authorization ...
-if pod trunk me | grep MaterialComponents ; then
-else
+if ! pod trunk me | grep -q 'MaterialComponnents'; then
   all_tests_ok=0
   echo
-  echo "Failed pod push authorization. Register an account and session: https://guides.cocoapods.org/making/getting-setup-with-trunk.html"
+  echo "Failed! Register an account and session: https://guides.cocoapods.org/making/getting-setup-with-trunk.html"
   echo "Continuing with next test..."
   echo
 fi
